//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora.ReferenciaServico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicoWeb.calculadora/", ConfigurationName="ReferenciaServico.ServicoWeb")]
    public interface ServicoWeb {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://servicoWeb.calculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="http://servicoWeb.calculadora/ServicoWeb/multiplicarRequest", ReplyAction="http://servicoWeb.calculadora/ServicoWeb/multiplicarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Calculadora.ReferenciaServico.multiplicarResponse multiplicar(Calculadora.ReferenciaServico.multiplicarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicoWeb.calculadora/ServicoWeb/multiplicarRequest", ReplyAction="http://servicoWeb.calculadora/ServicoWeb/multiplicarResponse")]
        System.Threading.Tasks.Task<Calculadora.ReferenciaServico.multiplicarResponse> multiplicarAsync(Calculadora.ReferenciaServico.multiplicarRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://servicoWeb.calculadora/)
        [System.ServiceModel.OperationContractAttribute(Action="http://servicoWeb.calculadora/ServicoWeb/somaRequest", ReplyAction="http://servicoWeb.calculadora/ServicoWeb/somaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Calculadora.ReferenciaServico.somaResponse soma(Calculadora.ReferenciaServico.somaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicoWeb.calculadora/ServicoWeb/somaRequest", ReplyAction="http://servicoWeb.calculadora/ServicoWeb/somaResponse")]
        System.Threading.Tasks.Task<Calculadora.ReferenciaServico.somaResponse> somaAsync(Calculadora.ReferenciaServico.somaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicar", WrapperNamespace="http://servicoWeb.calculadora/", IsWrapped=true)]
    public partial class multiplicarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public multiplicarRequest() {
        }
        
        public multiplicarRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicarResponse", WrapperNamespace="http://servicoWeb.calculadora/", IsWrapped=true)]
    public partial class multiplicarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public multiplicarResponse() {
        }
        
        public multiplicarResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="soma", WrapperNamespace="http://servicoWeb.calculadora/", IsWrapped=true)]
    public partial class somaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public somaRequest() {
        }
        
        public somaRequest(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="somaResponse", WrapperNamespace="http://servicoWeb.calculadora/", IsWrapped=true)]
    public partial class somaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public somaResponse() {
        }
        
        public somaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoWebChannel : Calculadora.ReferenciaServico.ServicoWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoWebClient : System.ServiceModel.ClientBase<Calculadora.ReferenciaServico.ServicoWeb>, Calculadora.ReferenciaServico.ServicoWeb {
        
        public ServicoWebClient() {
        }
        
        public ServicoWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculadora.ReferenciaServico.multiplicarResponse Calculadora.ReferenciaServico.ServicoWeb.multiplicar(Calculadora.ReferenciaServico.multiplicarRequest request) {
            return base.Channel.multiplicar(request);
        }
        
        public double multiplicar(double arg0, double arg1) {
            Calculadora.ReferenciaServico.multiplicarRequest inValue = new Calculadora.ReferenciaServico.multiplicarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Calculadora.ReferenciaServico.multiplicarResponse retVal = ((Calculadora.ReferenciaServico.ServicoWeb)(this)).multiplicar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculadora.ReferenciaServico.multiplicarResponse> Calculadora.ReferenciaServico.ServicoWeb.multiplicarAsync(Calculadora.ReferenciaServico.multiplicarRequest request) {
            return base.Channel.multiplicarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculadora.ReferenciaServico.multiplicarResponse> multiplicarAsync(double arg0, double arg1) {
            Calculadora.ReferenciaServico.multiplicarRequest inValue = new Calculadora.ReferenciaServico.multiplicarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Calculadora.ReferenciaServico.ServicoWeb)(this)).multiplicarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculadora.ReferenciaServico.somaResponse Calculadora.ReferenciaServico.ServicoWeb.soma(Calculadora.ReferenciaServico.somaRequest request) {
            return base.Channel.soma(request);
        }
        
        public double soma(double arg0, double arg1) {
            Calculadora.ReferenciaServico.somaRequest inValue = new Calculadora.ReferenciaServico.somaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Calculadora.ReferenciaServico.somaResponse retVal = ((Calculadora.ReferenciaServico.ServicoWeb)(this)).soma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculadora.ReferenciaServico.somaResponse> Calculadora.ReferenciaServico.ServicoWeb.somaAsync(Calculadora.ReferenciaServico.somaRequest request) {
            return base.Channel.somaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculadora.ReferenciaServico.somaResponse> somaAsync(double arg0, double arg1) {
            Calculadora.ReferenciaServico.somaRequest inValue = new Calculadora.ReferenciaServico.somaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Calculadora.ReferenciaServico.ServicoWeb)(this)).somaAsync(inValue);
        }
    }
}
